package vn.edu.vhu.ltdd.a5intent;
import android.content.*; import android.net.Uri; import android.os.Bundle; import android.util.Log; import android.widget.*;
import androidx.activity.result.ActivityResultLauncher; import androidx.activity.result.contract.ActivityResultContracts; import androidx.appcompat.app.AppCompatActivity; import androidx.core.content.IntentCompat;
public class MainActivity extends AppCompatActivity {
 private static final String TAG="A5_241A010591"; public static final String EXTRA_CONTACT="extra_contact", EXTRA_NGUOI_GUI="extra_nguoi_gui";
 private EditText edtHoTen,edtDienThoai,edtEmail; private TextView tvKetQuaTraVe;
 private final ActivityResultLauncher<Intent> chiTietLauncher=registerForActivityResult(new ActivityResultContracts.StartActivityForResult(), result->{ if(result.getResultCode()==RESULT_OK&&result.getData()!=null){Contact c=IntentCompat.getParcelableExtra(result.getData(),EXTRA_CONTACT,Contact.class);if(c!=null){edtHoTen.setText(c.getHoTen());tvKetQuaTraVe.setText(getString(R.string.returned,c.getHoTen()));Log.d(TAG,"Nhận kết quả: "+c.getHoTen());}}else tvKetQuaTraVe.setText(R.string.returned_cancel);});
 @Override protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);Log.d(TAG,"Main.onCreate");edtHoTen=findViewById(R.id.edtHoTen);edtDienThoai=findViewById(R.id.edtDienThoai);edtEmail=findViewById(R.id.edtEmail);tvKetQuaTraVe=findViewById(R.id.tvKetQuaTraVe);findViewById(R.id.btnChiTiet).setOnClickListener(v->moChiTiet());findViewById(R.id.btnGoi).setOnClickListener(v->goiDien());findViewById(R.id.btnWeb).setOnClickListener(v->moWeb());findViewById(R.id.btnChiaSe).setOnClickListener(v->chiaSe());xuLyChiaSeDen(getIntent());}
 @Override protected void onNewIntent(Intent i){super.onNewIntent(i);setIntent(i);xuLyChiaSeDen(i);}
 private void xuLyChiaSeDen(Intent i){if(Intent.ACTION_SEND.equals(i.getAction())&&"text/plain".equals(i.getType())){String s=i.getStringExtra(Intent.EXTRA_TEXT);if(s!=null)tvKetQuaTraVe.setText(getString(R.string.incoming_share,s));}}
 private void moChiTiet(){String h=edtHoTen.getText().toString().trim();if(h.isEmpty()){edtHoTen.setError(getString(R.string.err_empty));return;}Contact c=new Contact(h,edtDienThoai.getText().toString().trim(),edtEmail.getText().toString().trim());Intent i=new Intent(this,DetailActivity.class);i.putExtra(EXTRA_CONTACT,c);i.putExtra(EXTRA_NGUOI_GUI,TAG);chiTietLauncher.launch(i);overridePendingTransition(R.anim.slide_in_right,R.anim.slide_out_left);}
 private void goiDien(){String s=edtDienThoai.getText().toString().trim();if(s.isEmpty()){edtDienThoai.setError(getString(R.string.err_empty));return;}moAnToan(new Intent(Intent.ACTION_DIAL,Uri.parse("tel:"+s)));}
 private void moWeb(){moAnToan(new Intent(Intent.ACTION_VIEW,Uri.parse(getString(R.string.school_url))));}
 private void chiaSe(){Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_SUBJECT,getString(R.string.share_subject));i.putExtra(Intent.EXTRA_TEXT,getString(R.string.share_text,edtHoTen.getText().toString(),edtDienThoai.getText().toString()));try{startActivity(Intent.createChooser(i,getString(R.string.share_title)));}catch(ActivityNotFoundException e){Toast.makeText(this,R.string.err_no_app,Toast.LENGTH_SHORT).show();}}
 private void moAnToan(Intent i){try{startActivity(i);}catch(ActivityNotFoundException e){Toast.makeText(this,R.string.err_no_app,Toast.LENGTH_SHORT).show();Log.w(TAG,"Không có app xử lý",e);}}
 @Override protected void onStart(){super.onStart();Log.d(TAG,"Main.onStart");}@Override protected void onResume(){super.onResume();Log.d(TAG,"Main.onResume");}@Override protected void onPause(){Log.d(TAG,"Main.onPause");super.onPause();}@Override protected void onStop(){Log.d(TAG,"Main.onStop");super.onStop();}@Override protected void onRestart(){super.onRestart();Log.d(TAG,"Main.onRestart");}@Override protected void onDestroy(){Log.d(TAG,"Main.onDestroy");super.onDestroy();}
}
